provider "vault" {}

data "vault_generic_secret" "aws_auth" {
  path = "aws-tf/creds/deploy"
}

data "external" "region" {
  # workaround for Vault Github issue 1086
  # AWS keys generated by Vault not immediately available
  # on all AWS API endpoints.
  program = ["./delay-vault-aws"]
}

provider "aws" {
  region = "${data.external.region.result["region"]}"
  access_key = "${data.vault_generic_secret.aws_auth.data["access_key"]}"
  secret_key = "${data.vault_generic_secret.aws_auth.data["secret_key"]}"
}

module "nomadconsul" {
  source = "modules/nomadconsul"

  region            = "${var.region}"
  ami               = "${var.ami}"
  vpc_id            = "${var.vpc_id}"
  subnet_id         = "${var.subnet_id}"
  server_instance_type     = "${var.server_instance_type}"
  client_instance_type     = "${var.client_instance_type}"
  key_name          = "${var.key_name}"
  server_count      = "${var.server_count}"
  client_count      = "${var.client_count}"
  name_tag_prefix   = "${var.name_tag_prefix}"
  cluster_tag_value = "${var.cluster_tag_value}"
  owner_tag_value   = "${var.owner_tag_value}"
  ttl_tag_value     = "${var.ttl_tag_value}"
  token_for_nomad   = "${var.token_for_nomad}"
  vault_url         = "${var.vault_url}"
}
